
name: Deploy infra, test API
on:
  push:
    branches:
      - main
jobs:

  job-terraform:
    name: terraform deploy all infra
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Init
      id: init
      run: terraform init

    - name: apply
      id: apply
      run: terraform apply -auto-approve

  job-sync-site:
    name: upload html css
    runs-on: ubuntu-latest
    env:
      FILE: ./resume-site/*
      AWS_REGION: 'us-east-1'
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
    - uses: actions/checkout@v2
    - name: upload files
    uses: tpaschalis/s3-sync-action@master
    with:
      args: --acl public-read

  job-cypress:  
    name: Cypress Testing API
    runs-on: ubuntu-latest
    needs: job-terraform
    container: cypress/included:9.5.0
    steps:
      - uses: actions/checkout@v1
      - run: cypress run
