
name: Deploy infra, test API
on:
  push:
    branches:
      - main
jobs:

  job-terraform:
    name: terraform deploy all infra
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Init
      id: init
      run: terraform init

    - name: apply
      id: apply
      run: terraform apply -auto-approve
  
  job-sync-website:
    name: sync website files to s3 bucket
    runs-on: ubuntu-latest
    needs: job-terraform
    steps:
    - uses: actions/checkout@master
    # - uses: marcbacchi/cloud-resume-challenge@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'resume-site'      # optional: defaults to entire repository

  job-cypress:  
    name: Cypress Testing API
    runs-on: ubuntu-latest
    needs: job-sync-website
    container: cypress/included:9.5.0
    steps:
      - uses: actions/checkout@v1
      - run: cypress run
