name: Deploy infra, test API
on:
  push:
    branches:
      - main
jobs:
  cypress:  
    name: Cypress Test
    runs-on: ubuntu-latest
    container: cypress/included:9.5.0
    steps:
      - uses: actions/checkout@v1
      - run: cypress run
